# Generated by Django 4.2.20 on 2025-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=10)),
                ('data', models.DateField()),
                ('produtos_mais_procurados', models.TextField(blank=True, help_text='Apenas para relatórios semanais.', null=True)),
                ('sugestao_grade_produtos', models.TextField(blank=True, help_text='Apenas para relatórios mensais. Sugestão de retirada ou inserção na grade de produtos.', null=True)),
                ('feedback_geral', models.TextField()),
                ('acao_melhoria_mes', models.TextField(blank=True, help_text='O que fazer para melhorar esse mês.', null=True)),
                ('acao_correcao_semana', models.TextField(blank=True, help_text='O que podemos fazer para corrigir os erros da semana?', null=True)),
                ('colaborador_destaque', models.CharField(blank=True, help_text='Colaborador do mês com destaque dos principais fatores.', max_length=100, null=True)),
                ('feedback_organizacao', models.TextField(blank=True, help_text='Feedback sobre a organização da loja: produtos expostos, vitrine, limpeza, etc.', null=True)),
                ('logistica', models.TextField(blank=True, help_text='O que pode melhorar na logística.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
