# Generated by Django 4.2.20 on 2025-03-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='acao_melhoria_mes',
            field=models.TextField(blank=True, help_text='O que fazer para melhorar esse mês', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='colaborador_destaque',
            field=models.CharField(blank=True, help_text='Colaborador do mês e os principais fatores para esse destaque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback_geral',
            field=models.TextField(help_text='Feedback geral do período'),
        ),
        migrations.AlterField(
            model_name='report',
            name='logistica',
            field=models.TextField(blank=True, help_text='O que pode melhorar na logística', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='produtos_mais_procurados',
            field=models.TextField(blank=True, help_text='Produtos mais procurados (apenas para o semanal, se desejar manter a aba exclusiva, pode-se usar um campo separado)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sugestao_grade_produtos',
            field=models.TextField(blank=True, help_text='Sugestão de retirada ou inserção na grade de produtos da loja', null=True),
        ),
    ]
