# Generated by Django 4.2.20 on 2025-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_acao_melhoria_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='atendimento_online',
            field=models.TextField(blank=True, help_text='Feedback e avaliação do atendimento online', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='atendimento_presencial',
            field=models.TextField(blank=True, help_text='Feedback e avaliação do atendimento presencial', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='colaborador_destaque',
            field=models.CharField(blank=True, help_text='Colaborador do mês com destaque dos principais fatores', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback_organizacao',
            field=models.TextField(blank=True, help_text='Feedback sobre a organização da loja (produtos expostos, vitrine, limpeza, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='produtos_mais_procurados',
            field=models.TextField(blank=True, help_text='Produtos mais procurados (exclusivo do semanal)', null=True),
        ),
    ]
